In [3]:
from fomlads.evaluate.eval_regression import train_and_test_partition
from fomlads.evaluate.eval_regression import train_and_test_filter
from fomlads.evaluate.eval_regression import create_cv_folds

import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv('/Users/ash/Documents/Year 4/Foundations of Machine Learning/Project/Used Dataset.csv')

In [24]:
# FUNCTION 1

def inputs_and_targets(pdDataset):
    """
    Function separates inputs and targets in the dataset.
    
    """
    number_of_columns = len(pdDataset.axes[1])
    npDataset = pdDataset.to_numpy() # Convert dataset to a numpy array
    inputs = npDataset[: , :(number_of_columns - 1)] # Split numpy array since genres/targets are only in the last column
    targets = npDataset[: , (number_of_columns - 1)].astype('object')
    return inputs, targets

inputs_and_targets(df)

# CODE WITHOUT BEING A FUNCTION

# number_of_columns = len(df.axes[1])
# np_df = df.to_numpy()
# inputs = np_df[: , :(number_of_columns - 1)]
# targets = np_df[: , (number_of_columns - 1)].astype('object') 
# print(inputs)
# print(targets)

(array([[44, 0.00621, 0.711, ..., 0.0382, 142.065, 0.607],
        [34, 0.347, 0.729, ..., 0.184, 79.969, 0.287],
        [39, 0.918, 0.484, ..., 0.0346, 82.707, 0.206],
        ...,
        [51, 0.00597, 0.693, ..., 0.146, 131.079, 0.395],
        [65, 0.0831, 0.782, ..., 0.0441, 75.886, 0.354],
        [67, 0.102, 0.862, ..., 0.101, 99.201, 0.765]], dtype=object),
 array(['Jazz', 'Jazz', 'Jazz', ..., 'Hip-Hop', 'Hip-Hop', 'Hip-Hop'],
       dtype=object))

In [25]:
# FUNCTION 2

def train_and_validation_inputs_targets(pdDataset, cv_folds = 5, randomseed = 0):
    """
    Function takes dataset for the training/validation data, then creates n (= cv_folds) cross
    validation folds to use in different models.
    """

    np.random.seed(randomseed) # Use a random seed = 0 to ensure reproducability when creating cross validation folds

    inputs, targets = inputs_and_targets(pdDataset)
    
    folds = create_cv_folds(len(pdDataset), cv_folds) # Get n (= cv_folds) train and test filters from create_cv_folds to use cross validation
    
    train_inputs = []
    train_targets = []
    validation_inputs = []
    validation_targets = []
    
    for i in range(cv_folds): # Store train and validation inputs/targets as lists
        train_inputs1, train_targets1, validation_inputs1, validation_targets1 = train_and_test_partition(inputs, targets, folds[i][0], folds[i][1])
        train_inputs.append(train_inputs1)
        train_targets.append(train_targets1)
        validation_inputs.append(validation_inputs1)
        validation_targets.append(validation_targets1)
        
    return train_inputs, train_targets, validation_inputs, validation_targets

train_and_validation_inputs_targets(df, cv_folds = 5, randomseed = 0)

# CODE WITHOUT BEING A FUNCTION

# N = len(df)
# num_folds = 5
# np.random.seed(seed = 1)
# inputs, targets = inputs_and_targets(df)
# folds = create_cv_folds(N, num_folds)  
# train_inputs = []
# train_targets = []
# validation_inputs = []
# validation_targets = []
# for i in range(num_folds):
    # train_inputs1, train_targets1, validation_inputs1, validation_targets1 = train_and_test_partition(inputs, targets, folds[i][0], folds[i][1])
    # train_inputs.append(train_inputs1)
    # train_targets.append(train_targets1)
    # validation_inputs.append(validation_inputs1)
    # validation_targets.append(validation_targets1)
# print(train_inputs)
# print(train_targets)
# print(validation_inputs)
# print(validation_targets)

([array([[44, 0.00621, 0.711, ..., 0.0382, 142.065, 0.607],
         [34, 0.347, 0.729, ..., 0.184, 79.969, 0.287],
         [39, 0.918, 0.484, ..., 0.0346, 82.707, 0.206],
         ...,
         [72, 0.157, 0.709, ..., 0.055, 122.043, 0.113],
         [51, 0.00597, 0.693, ..., 0.146, 131.079, 0.395],
         [65, 0.0831, 0.782, ..., 0.0441, 75.886, 0.354]], dtype=object),
  array([[34, 0.347, 0.729, ..., 0.184, 79.969, 0.287],
         [39, 0.918, 0.484, ..., 0.0346, 82.707, 0.206],
         [36, 0.0345, 0.473, ..., 0.063, 104.694, 0.383],
         ...,
         [51, 0.00597, 0.693, ..., 0.146, 131.079, 0.395],
         [65, 0.0831, 0.782, ..., 0.0441, 75.886, 0.354],
         [67, 0.102, 0.862, ..., 0.101, 99.201, 0.765]], dtype=object),
  array([[44, 0.00621, 0.711, ..., 0.0382, 142.065, 0.607],
         [53, 0.501, 0.921, ..., 0.213, 123.043, 0.761],
         [32, 0.765, 0.696, ..., 0.0297, 131.924, 0.47],
         ...,
         [56, 0.133, 0.849, ..., 0.0516, 99.988, 0.629],
    

In [28]:
# FUNCTION 3

def accuracyscore(actual_target, predict_target):
    """
    Function calculates accuracy score by comparing the actual and predicted targets.
    
    """
    n = len(actual_target)
    score = 0
    for i in range(n):
        if actual_target[i] == predict_target[i]: # Calculate how many targets are correctly predicted
            score += 1
    accuracy = score / n # Divide number of correctly predicted targets by total for accuracy score
    return accuracy

In [27]:
# FUNCTION 4

def standardised_array(array):
    """
    Function takes an array and standardises the columns.
    
    """
    standard_array = array.copy() # Make a copy of the array and store it as the standardised array
    for i in range(array.shape[1]): # Standardise by going through each column
        mean = array[: , i].mean()
        std = array[: , i].std()
        standard_array[: , i] = (array[: , i] - mean) / std
    return standard_array